on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@latest

    - name: Compile LaTeX document
      run: latexmk -pdf -silent Implementation_Details.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: Implementation_Details.pdf
